codecov:
  require_ci_to_pass: no
  bot: cooperaj
  comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false  # if true: only post the comment if coverage changes
    after_n_builds: 4 #wait for 4 uploads then notify asap.
