version: "3.8"

volumes:
  webpack_dist:

services:

  # ---------------------------
  # Viewer Front

  viewer-web:
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.viewer-web.rule=Host(`viewer.docker`)

  viewer-app:
    environment:
      PHP_IDE_CONFIG: serverName=viewer-app-docker

  # ---------------------------
  # Actor Front

  actor-web:
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.actor-web.rule=Host(`actor.docker`)

  actor-app:
    environment:
      PHP_IDE_CONFIG: serverName=actor-app-docker

  # ---------------------------
  # API

  api-web:
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.api-web.rule=Host(`api.docker`)

  api-app:
    environment:
      PHP_IDE_CONFIG: serverName=api-app-docker

networks:
  proxy:
    external: true
