name: "[Docker] Jest unit tests web"

defaults:
  run:
    shell: bash

on:
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3
      - name: cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ./service-front/web/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**service-front/web/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: install dependencies
        run: |
          if [ ! -d service-front/web/node_modules ]; then
            cd ./service-front/web/ && npm ci
          fi
      - name: run tests with jest
        run: |
          cd service-front/web/
          mkdir -p ./test-results/junit
          ./node_modules/.bin/jest --ci --runInBand --reporters=default --reporters=jest-junit
      - name: test summary
        uses: test-summary/action@v1
        with:
          paths: |
            **/service-front/web/test-results/junit/results.xml
        if: always()
